'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { User } from '@supabase/supabase-js';
import { supabase } from '@/lib/supabase';

type Data={symbol:string;months:number;tradingDays:number;bars:number;lastPrice:number;lastDate:string;best:{tp:number;reentry:number;cycles:number;returnPct:number;avgDays:number};technical:{label:string;score:number;rsi14:number;macd:number;macdSignal:number;sma20:number;sma50:number;ema20:number};targetFromLast:number;reentryAfterTarget:number;error?:string};
type Position={symbol:string;entry_price:number|null;status:'watch'|'active';target_pct:number};
type StockState={symbol:string;data?:Data;loading:boolean;entry?:number|null;entryInput:string;targetPct?:number};
type RadarItem={symbol:string;price:number;score:number;verdict:'ALIM FIRSATI'|'İZLE'|'BEKLE'|'UZAK DUR';drawdown20:number;noNewLow:boolean;rsi14:number;rsiRising:boolean;volumeVeto:boolean;lowPrice:boolean;reason:string};
const money=(n:number)=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const pct=(n:number)=>`${n>=0?'+':''}%${n.toFixed(2)}`;
const CORE=['ASELS','THYAO'];

export default function Home(){
 const[user,setUser]=useState<User|null>(null),[authReady,setAuthReady]=useState(false),[authMsg,setAuthMsg]=useState('');
 const[months,setMonths]=useState(3),[positions,setPositions]=useState<Position[]>([]),[stocks,setStocks]=useState<Record<string,StockState>>({}),[newSymbol,setNewSymbol]=useState(''),[radar,setRadar]=useState<RadarItem[]>([]),[radarLoading,setRadarLoading]=useState(true);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{setUser(data.user);setAuthReady(true)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);setAuthReady(true)});return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{loadRadar()},[]);
 useEffect(()=>{if(user)loadPositions()},[user]);
 const symbols=useMemo(()=>positions.map(p=>p.symbol),[positions]);
 useEffect(()=>{if(user)symbols.forEach(s=>loadStock(s))},[user,months,symbols.join('|')]);
 async function login(email:string,password:string,signup=false){setAuthMsg('');const res=signup?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});if(res.error)setAuthMsg(res.error.message);else if(signup&&!res.data.session)setAuthMsg('Hesap oluşturuldu. E-posta doğrulaması gerekiyorsa gelen bağlantıyı aç.')}
 async function loadPositions(){if(!user)return;let{data}=await supabase.from('backtest_positions').select('symbol,entry_price,status,target_pct').order('symbol');if(!data?.length){await supabase.from('backtest_positions').upsert(CORE.map(symbol=>({user_id:user.id,symbol,status:'watch',target_pct:5})),{onConflict:'user_id,symbol'});({data}=await supabase.from('backtest_positions').select('symbol,entry_price,status,target_pct').order('symbol'))}setPositions((data||[]) as Position[])}
 async function loadRadar(){setRadarLoading(true);try{const r=await fetch('/api/radar',{cache:'no-store'}),j=await r.json();setRadar(j.items||[])}catch{setRadar([])}setRadarLoading(false)}
 async function loadStock(symbol:string){setStocks(p=>({...p,[symbol]:{...(p[symbol]||{symbol,entryInput:''}),loading:true}}));try{const r=await fetch(`/api/backtest?symbol=${symbol}&months=${months}`,{cache:'no-store'}),data=await r.json(),pos=positions.find(x=>x.symbol===symbol);setStocks(p=>({...p,[symbol]:{symbol,data,loading:false,entry:pos?.entry_price??null,targetPct:pos?.target_pct??data.best?.tp,entryInput:pos?.entry_price?String(pos.entry_price):p[symbol]?.entryInput||''}}))}catch{setStocks(p=>({...p,[symbol]:{symbol,data:{error:'Veri alınamadı'} as Data,loading:false,entry:null,entryInput:''}}))}}
 async function saveEntry(symbol:string,e:FormEvent){e.preventDefault();if(!user)return;const st=stocks[symbol],n=Number((st?.entryInput||'').replace(',','.'));if(!Number.isFinite(n)||n<=0||!st?.data)return;const targetPct=st.data.best.tp;const{error}=await supabase.from('backtest_positions').upsert({user_id:user.id,symbol,entry_price:n,status:'active',target_pct:targetPct,opened_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'user_id,symbol'});if(!error){await loadPositions();setStocks(p=>({...p,[symbol]:{...p[symbol],entry:n,targetPct}}))}}
 async function clearEntry(symbol:string){if(!user)return;await supabase.from('backtest_positions').update({entry_price:null,status:'watch',opened_at:null,updated_at:new Date().toISOString()}).eq('user_id',user.id).eq('symbol',symbol);await loadPositions();setStocks(p=>({...p,[symbol]:{...p[symbol],entry:null,entryInput:''}}))}
 async function addSymbol(e:FormEvent){e.preventDefault();if(!user)return;const s=newSymbol.trim().toUpperCase().replace(/[^A-Z0-9]/g,'');if(!s||symbols.includes(s))return;await supabase.from('backtest_positions').upsert({user_id:user.id,symbol:s,status:'watch',target_pct:5},{onConflict:'user_id,symbol'});setNewSymbol('');await loadPositions()}
 async function addRadarSymbol(s:string){if(!user||symbols.includes(s))return;await supabase.from('backtest_positions').upsert({user_id:user.id,symbol:s,status:'watch',target_pct:5},{onConflict:'user_id,symbol'});await loadPositions()}
 const active=positions.filter(p=>p.status==='active'&&p.entry_price),waiting=positions.filter(p=>p.status==='watch'||!p.entry_price);
 if(!authReady)return <main><div className="empty">Yükleniyor…</div></main>;
 if(!user)return <Login onSubmit={login} message={authMsg}/>;
 return <main>
  <header className="hero"><div><p className="eyebrow">BIST · SWING DESK</p><h1>Swing Board</h1><p className="sub">Kalıcı pozisyonlar, dinamik TP ve sade dip radarı.</p></div><div className="headerActions"><div className="period"><span>BACKTEST</span><select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={1}>1 ay · ~21 seans</option><option value={2}>2 ay · ~42 seans</option><option value={3}>3 ay · ~63 seans</option><option value={6}>6 ay · ~126 seans</option></select></div><button className="logout" onClick={()=>supabase.auth.signOut()}>Çıkış</button></div></header>
  <section className="overview"><div><span>Aktif pozisyon</span><strong>{active.length}</strong></div><div><span>Alım bekleyen</span><strong>{waiting.length}</strong></div><div><span>Takip edilen</span><strong>{positions.length}</strong></div><div><span>Veri</span><strong className="statusOk">Supabase</strong></div></section>
  <section className="sectionBlock"><div className="sectionHead"><div><span className="sectionKicker">PORTFÖY</span><h2>Aktif pozisyonlar</h2></div><span className="muted">TP takibi · kalıcı</span></div>{active.length?<div className="list">{active.map(p=><StockRow key={p.symbol} state={stocks[p.symbol]||{symbol:p.symbol,loading:true,entryInput:''}} onReload={()=>loadStock(p.symbol)} onSave={e=>saveEntry(p.symbol,e)} onClear={()=>clearEntry(p.symbol)} onInput={v=>setStocks(x=>({...x,[p.symbol]:{...x[p.symbol],symbol:p.symbol,loading:x[p.symbol]?.loading??false,entryInput:v}}))}/>)}</div>:<div className="empty">Henüz aktif pozisyon yok.</div>}</section>
  <section className="sectionBlock"><div className="sectionHead"><div><span className="sectionKicker">TAKİP</span><h2>Alım bekleyenler</h2></div><form className="addTicker" onSubmit={addSymbol}><input value={newSymbol} onChange={e=>setNewSymbol(e.target.value)} placeholder="Hisse kodu"/><button>Ekle</button></form></div><div className="list">{waiting.map(p=><StockRow key={p.symbol} state={stocks[p.symbol]||{symbol:p.symbol,loading:true,entryInput:''}} onReload={()=>loadStock(p.symbol)} onSave={e=>saveEntry(p.symbol,e)} onClear={()=>clearEntry(p.symbol)} onInput={v=>setStocks(x=>({...x,[p.symbol]:{...x[p.symbol],symbol:p.symbol,loading:x[p.symbol]?.loading??false,entryInput:v}}))}/>)}</div></section>
  <section className="sectionBlock radarSection"><div className="sectionHead"><div><span className="sectionKicker">RADAR V2</span><h2>Düşmüş ama frenlemiş hisseler</h2></div><button className="radarRefresh" onClick={loadRadar}>↻ Yenile</button></div><p className="radarNote"><b>R = D + B + M.</b> D: zirveden %5–15 düşüş · B: son 3 seansta yeni dip yok · M: RSI yukarı dönüyor. <b>Yeni dip + artan satış hacmi = UZAK DUR.</b></p><div className="radarTable"><div className="radarHeader"><span>#</span><span>Hisse</span><span>Fiyat</span><span>Düşüş</span><span>Dip durdu</span><span>RSI</span><span>RSI yön</span><span>Skor</span><span>Karar</span><span></span></div>{radarLoading?<div className="radarLoading">Radar taranıyor…</div>:radar.map((r,i)=><div className="radarLine" key={r.symbol}><span className="rank">{i+1}</span><strong>{r.symbol}</strong><span>₺{money(r.price)}</span><span className={r.drawdown20<=-5&&r.drawdown20>=-15?'positive':''}>%{r.drawdown20.toFixed(1)}</span><span>{r.noNewLow?'Evet':'Hayır'}</span><span>{r.rsi14.toFixed(0)}</span><span>{r.rsiRising?'↑':'→/↓'}</span><b>{r.score}/3</b><span className={`radarVerdict ${r.verdict==='ALIM FIRSATI'?'opportunity':r.verdict==='UZAK DUR'?'danger':''}`}>{r.verdict}</span><button disabled={symbols.includes(r.symbol)||r.verdict==='UZAK DUR'} onClick={()=>addRadarSymbol(r.symbol)}>{symbols.includes(r.symbol)?'Takipte':'Takibe al'}</button></div>)}</div></section>
  <footer><span>Pozisyonlar artık Supabase’de kalıcıdır.</span><span>Backtest ve radar geçmiş veriye dayanır · yatırım tavsiyesi değildir.</span></footer>
 </main>
}

function Login({onSubmit,message}:{onSubmit:(e:string,p:string,s?:boolean)=>void;message:string}){const[email,setEmail]=useState(''),[password,setPassword]=useState('');return <main className="loginMain"><section className="loginCard"><p className="eyebrow">BACKTEST STOCK</p><h1>Swing Board</h1><p className="sub">Pozisyonların artık cihazda değil, hesabında saklanır.</p><form onSubmit={e=>{e.preventDefault();onSubmit(email,password,false)}}><input type="email" required placeholder="E-posta" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" required minLength={6} placeholder="Şifre" value={password} onChange={e=>setPassword(e.target.value)}/><button>Giriş yap</button></form><button className="signupBtn" onClick={()=>onSubmit(email,password,true)}>Hesap oluştur</button>{message&&<p className="authMsg">{message}</p>}</section></main>}

function StockRow({state,onReload,onSave,onClear,onInput}:{state:StockState;onReload:()=>void;onSave:(e:FormEvent)=>void;onClear:()=>void;onInput:(v:string)=>void}){const{symbol,data,loading,entry,entryInput,targetPct}=state;if(loading)return <article className="stockRow loadingRow"><div className="pulse"/></article>;if(!data||data.error)return <article className="stockRow"><div className="rowMain"><strong>{symbol}</strong><span className="error">{data?.error||'Veri alınamadı'}</span></div><button className="rowBtn" onClick={onReload}>Tekrar dene</button></article>;const tp=entry?(targetPct??data.best.tp):data.best.tp,posReturn=entry?(data.lastPrice/entry-1)*100:0,target=entry?entry*(1+tp/100):data.targetFromLast,remaining=entry?Math.max(0,(target/data.lastPrice-1)*100):null,reached=!!entry&&data.lastPrice>=target,progress=entry?Math.max(0,Math.min(100,(posReturn/tp)*100)):0;return <article className="stockRow"><div className="rowMain"><div className="tickerLine"><strong>{symbol}</strong><span className={`badge ${data.technical.label.includes('Al')?'buy':data.technical.label.includes('Sat')?'sell':''}`}>{data.technical.label}</span></div><div className="lastPrice">₺{money(data.lastPrice)}</div><small>{data.lastDate} · RSI {data.technical.rsi14.toFixed(0)}</small></div><div className="rowMetric"><span>TP</span><strong>+%{tp.toFixed(2)}</strong></div><div className="rowMetric"><span>Yeniden al</span><strong>-%{data.best.reentry.toFixed(2)}</strong></div>{entry?<div className="positionStrip"><div><span>Getiri</span><b className={posReturn>=0?'positive':'negative'}>{pct(posReturn)}</b></div><div><span>Hedef</span><b>₺{money(target)}</b></div><div><span>{reached?'Durum':'Kalan'}</span><b className={reached?'hit':''}>{reached?'HEDEF':`%${remaining?.toFixed(2)}`}</b></div><div className="thinProgress"><i style={{width:`${progress}%`}}/></div><button className="ghostBtn" onClick={onClear}>Pozisyonu kapat</button></div>:<form className="quickEntry" onSubmit={onSave}><input inputMode="decimal" value={entryInput} onChange={e=>onInput(e.target.value)} placeholder="Alış fiyatı"/><button>Pozisyon aç</button></form>}<button className="iconBtn refreshIcon" onClick={onReload}>↻</button></article>}
