'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';

type Data = { symbol:string; months:number; tradingDays:number; bars:number; lastPrice:number; lastDate:string; best:{tp:number;reentry:number;cycles:number;returnPct:number;avgDays:number}; technical:{label:string;score:number;rsi14:number;macd:number;macdSignal:number;sma20:number;sma50:number;ema20:number}; targetFromLast:number; reentryAfterTarget:number; error?:string };
type StockState={symbol:string;data?:Data;loading:boolean;entry?:number|null;entryInput:string};
type RadarItem={symbol:string;price:number;score:number;verdict:'Fırsat'|'İzle'|'Bekle';drawdown20:number;rsi14:number;avgSwing20:number;maxMove20:number;lowPrice:boolean;reason:string};
const money=(n:number)=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const pct=(n:number)=>`${n>=0?'+':''}%${n.toFixed(2)}`;
const DEFAULT_SYMBOLS=['ASELS','THYAO'];

export default function Home(){
 const[months,setMonths]=useState(3),[symbols,setSymbols]=useState<string[]>(DEFAULT_SYMBOLS),[stocks,setStocks]=useState<Record<string,StockState>>({}),[newSymbol,setNewSymbol]=useState(''),[radar,setRadar]=useState<RadarItem[]>([]),[radarLoading,setRadarLoading]=useState(true);
 useEffect(()=>{const saved=localStorage.getItem('swing-symbols');if(saved){try{const arr=JSON.parse(saved);if(Array.isArray(arr)&&arr.length)setSymbols(arr)}catch{}}loadRadar()},[]);
 useEffect(()=>{localStorage.setItem('swing-symbols',JSON.stringify(symbols))},[symbols]);
 useEffect(()=>{symbols.forEach(loadStock)},[months,symbols.join('|')]);
 async function loadRadar(){setRadarLoading(true);try{const r=await fetch('/api/radar',{cache:'no-store'}),j=await r.json();setRadar(j.items||[])}catch{setRadar([])}setRadarLoading(false)}
 async function loadStock(symbol:string){setStocks(p=>({...p,[symbol]:{...(p[symbol]||{symbol,entryInput:''}),loading:true}}));try{const r=await fetch(`/api/backtest?symbol=${symbol}&months=${months}`,{cache:'no-store'}),data=await r.json(),saved=localStorage.getItem(`position-entry-${symbol}`),entry=saved&&Number(saved)>0?Number(saved):null;setStocks(p=>({...p,[symbol]:{symbol,data,loading:false,entry,entryInput:entry?String(entry):p[symbol]?.entryInput||''}}))}catch{setStocks(p=>({...p,[symbol]:{symbol,data:{error:'Veri alınamadı'} as Data,loading:false,entry:null,entryInput:''}}))}}
 function saveEntry(symbol:string,e:FormEvent){e.preventDefault();const n=Number((stocks[symbol]?.entryInput||'').replace(',','.'));if(!Number.isFinite(n)||n<=0)return;localStorage.setItem(`position-entry-${symbol}`,String(n));setStocks(p=>({...p,[symbol]:{...p[symbol],entry:n}}))}
 function clearEntry(symbol:string){localStorage.removeItem(`position-entry-${symbol}`);setStocks(p=>({...p,[symbol]:{...p[symbol],entry:null,entryInput:''}}))}
 function addSymbol(e:FormEvent){e.preventDefault();const s=newSymbol.trim().toUpperCase().replace(/[^A-Z0-9]/g,'');if(!s||symbols.includes(s))return;setSymbols(p=>[...p,s]);setNewSymbol('')}
 function addRadarSymbol(s:string){if(!symbols.includes(s))setSymbols(p=>[...p,s])}
 function removeSymbol(s:string){if(DEFAULT_SYMBOLS.includes(s))return;setSymbols(p=>p.filter(x=>x!==s));localStorage.removeItem(`position-entry-${s}`)}
 const active=useMemo(()=>symbols.filter(s=>stocks[s]?.entry),[symbols,stocks]),waiting=useMemo(()=>symbols.filter(s=>!stocks[s]?.entry),[symbols,stocks]);
 return <main>
  <header className="hero"><div><p className="eyebrow">BIST · SWING DESK</p><h1>Swing Board</h1><p className="sub">Pozisyonlar, alım bekleyenler ve otomatik fırsat radarı.</p></div><div className="period"><span>BACKTEST</span><select value={months} onChange={e=>setMonths(Number(e.target.value))}><option value={1}>1 ay · ~21 seans</option><option value={2}>2 ay · ~42 seans</option><option value={3}>3 ay · ~63 seans</option><option value={6}>6 ay · ~126 seans</option></select></div></header>
  <section className="overview"><div><span>Aktif pozisyon</span><strong>{active.length}</strong></div><div><span>Alım bekleyen</span><strong>{waiting.length}</strong></div><div><span>Takip edilen</span><strong>{symbols.length}</strong></div><div><span>Bildirim</span><strong className="statusOk">Telegram</strong></div></section>
  <section className="sectionBlock"><div className="sectionHead"><div><span className="sectionKicker">PORTFÖY</span><h2>Aktif pozisyonlar</h2></div><span className="muted">TP takibi</span></div>{active.length?<div className="list">{active.map(s=><StockRow key={s} state={stocks[s]} onReload={()=>loadStock(s)} onSave={e=>saveEntry(s,e)} onClear={()=>clearEntry(s)} onInput={v=>setStocks(p=>({...p,[s]:{...p[s],entryInput:v}}))}/>)}</div>:<div className="empty">Henüz aktif pozisyon yok.</div>}</section>
  <section className="sectionBlock"><div className="sectionHead"><div><span className="sectionKicker">TAKİP</span><h2>Alım bekleyenler</h2></div><form className="addTicker" onSubmit={addSymbol}><input value={newSymbol} onChange={e=>setNewSymbol(e.target.value)} placeholder="Hisse kodu"/><button>Ekle</button></form></div><div className="list">{waiting.map(s=><StockRow key={s} state={stocks[s]||{symbol:s,loading:true,entryInput:''}} onReload={()=>loadStock(s)} onSave={e=>saveEntry(s,e)} onClear={()=>clearEntry(s)} onInput={v=>setStocks(p=>({...p,[s]:{...p[s],symbol:s,loading:p[s]?.loading??true,entryInput:v}}))} onRemove={!DEFAULT_SYMBOLS.includes(s)?()=>removeSymbol(s):undefined}/>)}</div></section>
  <section className="sectionBlock radarSection"><div className="sectionHead"><div><span className="sectionKicker">FIRSAT TARAMASI</span><h2>Radar</h2></div><button className="radarRefresh" onClick={loadRadar}>↻ Yenile</button></div><p className="radarNote"><b>Ucuzluk burada nominal fiyat değildir.</b> Radar, hissenin kendi son 20 seansındaki zirvesine göre geri çekilmesini, RSI seviyesini ve günlük hareketlerinin swing üretecek kadar canlı ama pump/dump olmayacak kadar kontrollü olmasını puanlar. 100 TL altı sadece küçük bir ek puandır.</p>
  <div className="radarTable"><div className="radarHeader"><span>#</span><span>Hisse</span><span>Fiyat</span><span>20g zirveden</span><span>RSI</span><span>Ort. hareket</span><span>Max gün</span><span>Skor</span><span>Karar</span><span></span></div>{radarLoading?<div className="radarLoading">Radar taranıyor…</div>:radar.map((r,i)=><div className="radarLine" key={r.symbol}><span className="rank">{i+1}</span><strong>{r.symbol}</strong><span>₺{money(r.price)}</span><span className={r.drawdown20<=-4?'positive':''}>%{r.drawdown20.toFixed(1)}</span><span>{r.rsi14.toFixed(0)}</span><span>%{r.avgSwing20.toFixed(1)}</span><span>%{r.maxMove20.toFixed(1)}</span><b>{r.score}/11</b><span className={`radarVerdict ${r.verdict==='Fırsat'?'opportunity':''}`}>{r.verdict}</span><button disabled={symbols.includes(r.symbol)} onClick={()=>addRadarSymbol(r.symbol)}>{symbols.includes(r.symbol)?'Takipte':'Takibe al'}</button></div>)}</div></section>
  <footer><span>Radar aşırı spekülatif küçük hisseleri havuza almaz.</span><span>Backtest ve radar geçmiş veriye dayanır · yatırım tavsiyesi değildir.</span></footer>
 </main>
}
function StockRow({state,onReload,onSave,onClear,onInput,onRemove}:{state:StockState;onReload:()=>void;onSave:(e:FormEvent)=>void;onClear:()=>void;onInput:(v:string)=>void;onRemove?:()=>void}){const{symbol,data,loading,entry,entryInput}=state;if(loading)return <article className="stockRow loadingRow"><div className="pulse"/></article>;if(!data||data.error)return <article className="stockRow"><div className="rowMain"><strong>{symbol}</strong><span className="error">{data?.error||'Veri alınamadı'}</span></div><button className="rowBtn" onClick={onReload}>Tekrar dene</button>{onRemove&&<button className="iconBtn" onClick={onRemove}>×</button>}</article>;const posReturn=entry?(data.lastPrice/entry-1)*100:0,target=entry?entry*(1+data.best.tp/100):data.targetFromLast,remaining=entry?Math.max(0,(target/data.lastPrice-1)*100):null,reached=!!entry&&data.lastPrice>=target,progress=entry?Math.max(0,Math.min(100,(posReturn/data.best.tp)*100)):0;return <article className="stockRow"><div className="rowMain"><div className="tickerLine"><strong>{symbol}</strong><span className={`badge ${data.technical.label.includes('Al')?'buy':data.technical.label.includes('Sat')?'sell':''}`}>{data.technical.label}</span></div><div className="lastPrice">₺{money(data.lastPrice)}</div><small>{data.lastDate} · RSI {data.technical.rsi14.toFixed(0)}</small></div><div className="rowMetric"><span>TP</span><strong>+%{data.best.tp.toFixed(2)}</strong></div><div className="rowMetric"><span>Yeniden al</span><strong>-%{data.best.reentry.toFixed(2)}</strong></div>{entry?<div className="positionStrip"><div><span>Getiri</span><b className={posReturn>=0?'positive':'negative'}>{pct(posReturn)}</b></div><div><span>Hedef</span><b>₺{money(target)}</b></div><div><span>{reached?'Durum':'Kalan'}</span><b className={reached?'hit':''}>{reached?'HEDEF':`%${remaining?.toFixed(2)}`}</b></div><div className="thinProgress"><i style={{width:`${progress}%`}}/></div><button className="ghostBtn" onClick={onClear}>Pozisyonu kapat</button></div>:<form className="quickEntry" onSubmit={onSave}><input inputMode="decimal" value={entryInput} onChange={e=>onInput(e.target.value)} placeholder="Alış fiyatı"/><button>Pozisyon aç</button></form>}<button className="iconBtn refreshIcon" onClick={onReload}>↻</button>{onRemove&&<button className="iconBtn removeIcon" onClick={onRemove}>×</button>}</article>}
